version: "3"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_LOGIN:?USERNAME_MISSING}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:?PASSWORD_MISSING}
    volumes:
      - meeting-engineDB:/data/db
      - meeting-engineDB:/data/configdb
    ports:
      - 27017:27017
  postfix:
    image: boky/postfix
    restart: always
    environment:
      HOSTNAME: ${SMTP_HOST}
      ALLOWED_SENDER_DOMAINS: ${SMTP_ALLOWED_SENDER_DOMAINS}
  meeting:
    build: .
    env_file:
      - .env
    depends_on:
      - mongo
      - postfix
    ports:
      - 3000:3000
    restart: always

volumes:
  meeting-engineDB:
